dist: xenial
services:
- docker
python:
  - "3.9-slim"
before_script:
      -  pip install docker
      -  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
script:
  - docker build -t kyamajir123/vote ./vote
  - docker push kyamajir123/vote:latest
